### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by kast-g** [rahulsushilsharma/huggingface-chat#34]
I am using in node.js with this code 

import("huggingface-chat").then(module => {
    const { Login, ChatBot } = module;
    const EMAIL = "email";
    const PASSWD = "password";
    const cachePath = "./login_cache/";

    async function main() {
        try {
            const signin = new Login(EMAIL, PASSWD);
            const res = await signin.login(cachePath); // default path is ./login_cache/
            const chat = new ChatBot(res); // res is cookies which is required for subsequent aip calls
            const data = await chat.chat("who am i"); // Default model is "meta-llama/Llama-2-70b-chat-hf"
            
            // Create a reader for the stream
            let reader = data.stream.getReader();

            // Continuously read from the stream until it's done
            while (true) {
                const { done, value } = await reader.read();
                if (done) break; // The streaming has ended.
                console.log(value); // Log each chunk of data from the stream
            }
        } catch (error) {
            console.error("An error occurred:", error);
        }
    }

    main();
});

It is just generating new chats and nothing else.

**Comment by rahulsushilsharma** [comment]
Your code should be working I think there is a issue with the package or apis will need to check and see

**Comment by rahulsushilsharma** [comment]
yup the issue with huggingface chat apis 
```json
 data: { type: 'error', error: { message: 'Internal Error' }
 ```
 will need to check what changed

**Comment by kast-g** [comment]
Any fix?

**Comment by rahulsushilsharma** [comment]
hi sorry am little sick rn won't be able to work for sometime.

**Comment by Halo333X** [comment]
🙏

**Comment by Halo333X** [comment]
Any fix?

**Comment by rahulsushilsharma** [comment]
hi yea got the fix the api structure is changed and now they are validating message id server side i think, I added a Maintenance note on the lib and working on the fix

**Comment by rahulsushilsharma** [comment]
in final testing before publishing, need to add deprecation notice for older versions

**Comment by kast-g** [comment]
no worries I already made the hugging chat api by myself.
