### ISSUE TITLE
ERROR RETURNING RESPONSE

### ISSUE THREAD

**Issue by Halo333X** [rahulsushilsharma/huggingface-chat#50]
Currently, it doesn't show any error, but it's not returning something, it's a void message.
![image](https://github.com/user-attachments/assets/805ad849-feb0-435a-8504-e93dd4f1e5b3)

**Comment by rahulsushilsharma** [comment]
sorry for the late response was very busy with work, let me check on it

**Comment by Halo333X** [comment]
^^

**Comment by rahulsushilsharma** [comment]
fix
